# fly.toml file generated for koalamania on 2022-11-27T08:42:43+09:00

app = "koalamania"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  MY_SPECIAL_ENV = "some_value"
  MAX_PLAYER_COUNT = "15"
  AUTO_LOGIN_KEY = "+*tani$tsuba\\katsu-hama!"
  CLOUD_API_KEY = "222873739668934"
  CLOUD_API_SECRET = "kA_QQZ854E_YIZ7N5G10_lHzhzE"
  CLOUD_NAME = "honx7tf4c"
  CLOUDINARY_URL = "cloudinary://222873739668934:kA_QQZ854E_YIZ7N5G10_lHzhzE@honx7tf4c"
  TWITTER_API = "dTmokIaLxuChRxlSGyvYCmN2m"
  TWITTER_CALLBACK_URL = "http://127.0.0.1:8080/oauth/twitter/access"
  TWITTER_SECRET = "iS27Jp0Dg7nntDiBjyn0aTc7ert1kUlQOAScwHpSD0PGVYTw9K"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
