com:
  cloudinary:
    api_key: ${CLOUD_API_KEY}
    api_secret: ${CLOUD_API_SECRET}
    cloud_name: ${CLOUD_NAME}
    image:
      url: https://res.cloudinary.com/honx7tf4c/image/upload/animal/

server:
    port: ${PORT:8080}

spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${POSTGRES_PASS}
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
  flyway:
    enabled: true
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    url:  ${POSTGRES_URL}
    baseline-on-migrate: true # 既にあるテーブルなどがあるデータベースでもマイグレーションを実行する
    baseline-version: 0	

  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  social:
    twitter:
      app-id: ${TWITTER_API}
      app-secret: ${TWITTER_SECRET}
      callback-url: ${TWITTER_CALLBACK_URL}
      autoLoginKey: ${AUTO_LOGIN_KEY}
      
  messages:
    basename: messages, ValidationMessages

